In [1]:
import numpy as np

In [2]:
n = 5 
s = np.array(range(n))

In [3]:
s

array([0, 1, 2, 3, 4])

In [10]:
e  = list(bin(2))[2:]

In [11]:
e

['1', '0']

In [14]:
e = np.array(e) == '1'

In [15]:
e

array([ True, False], dtype=bool)

In [17]:
print(s[n-len(e):][e])

[3]


In [19]:
# 所有代码
import numpy as np
n = 5
s = np.array(range(n))
for i in range(2**n):
    e = list(bin(i))[2:]
    e = np.array(e) == '1'
    print(s[n-len(e):][e])

[]
[4]
[3]
[3 4]
[2]
[2 4]
[2 3]
[2 3 4]
[1]
[1 4]
[1 3]
[1 3 4]
[1 2]
[1 2 4]
[1 2 3]
[1 2 3 4]
[0]
[0 4]
[0 3]
[0 3 4]
[0 2]
[0 2 4]
[0 2 3]
[0 2 3 4]
[0 1]
[0 1 4]
[0 1 3]
[0 1 3 4]
[0 1 2]
[0 1 2 4]
[0 1 2 3]
[0 1 2 3 4]
